import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeInit } from "../../.flowbite-react/init";
import ConditionalLayout from "@/components/ConditionalLayout";
import { SessionProvider } from 'next-auth/react'

const geistSans = localFont({
  src: '../../node_modules/geist/dist/fonts/geist-sans/Geist-Regular.woff2',
  variable: '--font-geist',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "TAMVEMS",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/favicon.ico' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    shortcut: '/favicon.ico',
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180' },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geistSans.variable}>
      <body className="font-sans antialiased min-h-screen flex flex-col">
        <ThemeInit />
        <SessionProvider>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </SessionProvider>
      </body>
    </html>
  );
}
